# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08caccb33ecfb2ea4688fd4dffe5dd987a4fde44cac7be0a3edbf21465bf8ce62120e9fce907a1987512c81ae366a4b11c080c9f9b116f138594ecd7d5e309ea

test:
  secret_key_base: 3542d739c74cb6b0c426f5bfaefce00eafbd59c69caa69a8dddea2376bc7dd2bac8521a063a65c770cbbc67a788c6f54c6fc3dadbc106fc9b74eab573b42764f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
